// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaAPI.Datos;

#nullable disable

namespace VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240626000824_InsercionData")]
    partial class InsercionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaAPI.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle villa",
                            FechaActualizacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6372),
                            FechaCreacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6362),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa vista a la playa",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalle villa",
                            FechaActualizacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6374),
                            FechaCreacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6373),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa galante",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "",
                            Detalle = "Detalle villa",
                            FechaActualizacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6376),
                            FechaCreacion = new DateTime(2024, 6, 25, 19, 8, 24, 468, DateTimeKind.Local).AddTicks(6375),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa Nuvea",
                            Ocupantes = 4,
                            Tarifa = 200.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
